### ISSUE TITLE
Maven coordinates in the README are incorrect

### ISSUE THREAD

**Issue by davidkuster** [azam/ulidj#1]
As per https://mvnrepository.com/artifact/io.azam.ulidj/ulidj/1.0.0 correct value is:

    <dependency>
        <groupId>io.azam.ulidj</groupId>
        <artifactId>ulidj</artifactId>
        <version>1.0.0</version>
    </dependency>

Note groupId of `io.azam.ulidj` vs `io.azam` in the readme.

**Comment by azam** [comment]
Oops. Nice catch!
