### ISSUE TITLE
Support Same-Millisecond Monotonic Increments

### ISSUE THREAD

**Issue by VaughnVernon** [azam/ulidj#6]
Thanks for your work on this, @azam and @jkugiya.

I think that by making the implementation instance based (rather than all static methods), it would be quite straightforward to support monotonic increments within the random part during the same millisecond:

https://github.com/ulid/spec#monotonicity

Of course it could also be supported by requiring the client to pass another parameter. This approach seems clumsy, though.

In case you are concerned about collisions across distributed nodes, I found this:

https://medium.com/zendesk-engineering/how-probable-are-collisions-with-ulids-monotonic-option-d604d3ed2de

BTW, the two other Java implementations support monotonic increments, but both seem to increment the timestamp rather than the random part. That seems very wrong to me.

**Comment by ckamzn** [comment]
I'd also like to see this implemented - sorry I don't have the bandwidth to contribute.

NOTE: Unless I'm mistaken, Sulky [supports monotonicity](https://github.com/huxi/sulky/issues/3#issuecomment-410759126) in the specified way, incrementing the least significant bits (the random bits) [1](https://github.com/huxi/sulky/blob/2845a254cbf188f8221235cb875d17bf074fcfea/sulky-ulid/src/main/java/de/huxhorn/sulky/ulid/ULID.java#L158), [2](https://github.com/huxi/sulky/blob/2845a254cbf188f8221235cb875d17bf074fcfea/sulky-ulid/src/main/java/de/huxhorn/sulky/ulid/ULID.java#L302).

**Comment by azam** [comment]
@ckamzn @VaughnVernon 
Monotonic instance implemented as `MonotonicULID` instance you can generate monotonic ULID's from there. Will be released as v1.0.3.

Thank you for your patience!
